[package]
name = "chap19"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-new = "0.5.9"
hello_macro_derive = {path = "../chap19_5_hello_macro_derive"}